on: workflow_dispatch
name: 🚀 Deploy website manually
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: wangyucode/sftp-upload-action@v3
        with:
          host: ${{ vars.FTP_SERVER }}
          port: 23
          username: ${{ vars.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "./"
          remoteDir: "./"
          exclude: |
            .*/**